# Generated by Django 4.2 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('resume_size', models.FloatField()),
            ],
        ),
    ]
