# Generated by Django 4.2 on 2026-02-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_size',
        ),
    ]
